services:
  app:
    container_name: fastapi-server
    build:
      context: .
      dockerfile: ./infra/Dockerfile
    command: fastapi run src/app/main.py --port ${APP_PORT}
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    container_name: postgresql
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "${RESIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  celery-worker:
    container_name: celery-worker
    build:
      context: .
      dockerfile: ./infra/Dockerfile
    command: celery -A src.celery_app worker --loglevel=info
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: unless-stopped

  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: ./infra/Dockerfile
    command: celery -A src.celery_app beat --loglevel=info
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
