[project]
name = "pet-media-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "celery[redis]>=5.6.2",
    "fastapi[standard]>=0.129.0",
    "pydantic-settings>=2.13.1",
    "sqlalchemy[asyncio]>=2.0.46",
]

[dependency-groups]
dev = [
    "celery-types>=0.24.0",
    "factory-boy>=3.3.3",
    "httpx>=0.28.1",
    "mypy>=1.19.1",
    "prek>=0.3.3",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-xdist>=3.8.0",
    "ruff>=0.15.1",
    "rust-just>=1.46.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
src = ["src"]
include = ["src/**/*.py"]
line-length = 100
fix = true

[tool.ruff.lint]
fixable = ["ALL"]
select = ["ALL"]
ignore = [
    "D",       # Missing docstring
    "Q000",    # Use specified quotes for inline strings
    "Q003",    # Avoid escaped quotes
    "COM812",  # Enforce trailing commas
    "EM101",   # Exception must not use a string literal, assign to variable first
    "TRY003",  # Avoid specifying long messages outside the exception class,
    "PLW0108", # Avoid unnesessary lambda
]

[tool.ruff.lint.per-file-ignores]
"src/alembic/env.py" = [
    "INP001", # Namespace package
    "TC002",  # Third-party imports in type-checking
    "ERA001", # Commented-out code
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.mypy]
plugins = ["pydantic.mypy"]
files = ["src/**/*.py"]

explicit_package_bases = true
show_error_codes = true
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true

warn_unused_configs = true
warn_return_any = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_incomplete_stub = true

disallow_untyped_defs = true
disallow_untyped_calls = true
disallow_incomplete_defs = true


[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
